print("Please enter the following information: \n")

firstName = str(input("First name: "))
lastName = str(input("Last name: ").upper())
email = str(input("Email address: ").lower())
phone = str(input("Phone number: "))
jobTitle = str(input("Job title: ").capitalize())
idNumber = str(input("ID Number: "))

hair = str(input("Hair color: "))
eyes = str(input("Eyes color: "))
month = str(input("Starting Month: "))
training = str(input("Completed additional training? "))

print("The ID Card is:")
print("----------------------------------------\n")
print("{}, {}".format(lastName, firstName))
print(jobTitle)
print(idNumber,"\n")
print(email)
print(phone, "\n")
print(f"Hair: {hair:15} Eyes: {eyes}")
print(f"Month: {month:14} Training: {training}")
print("----------------------------------------\n")